```{r}
library(tidyverse)
library(ggpubr)

files<-list.files("/media/Lawrenson_Lab_NAS/uthscsa/group_data/CosMx_temp",full.names = T)
files<-files[str_detect(files,"SL")]
files<-list.files(files,full.names = T)
files<-files[str_detect(files,"meta")]
data<-lapply(files,data.table::fread)
#8.5 GB 
names(data)<-str_remove_all(files,".+temp/|/meta.+")
data<-lapply(data,function(i) i%>%filter(CD10>0|KRT8>0|PGP95>0|CD45>0|CD20>0))

```

```{r}
data<-lapply(data,function(x) 
    x%>%pivot_longer(AF:CD20,names_to = "protein",values_to = "signal")%>%
    filter(signal>0))
data<-lapply(data,function(x) 
    x%>%group_by(protein)%>%mutate(normi=signal/max(signal)))

set_threshold<-function(values){
     if(skewness(values)<2){th<-quantile(values,0.5)}
     else{
         d<-density(values)
         th<-which(diff(d$y)<0)
	 th<-max(which(th==min(th):max(th)))
         th<-d$x[th]}
     return(th)}
thr<-lapply(data,function(x) 
    sapply(unique(x$protein),function(y) 
        set_threshold(x$normi[x$protein==y])))
thr<-lapply(thr,function(x)
    x%>%as.matrix%>%as.data.frame%>%rownames_to_column("protein")%>%
    mutate(protein=str_remove(protein,"\\..+"),th=V1)%>%select(protein,th))

filtered<-lapply(names(data),function(x) 
    data[[x]]%>%left_join(thr[[x]])%>%filter(normi>th&protein!="AF"))
names(filtered)<-names(data)
```

```{r}
protecols<-c(CD10="#327919FF",CD20="#FFFF00FF",CD45="#6399B2FF",KRT8="#F00000FF",PGP95="#F500F5FF",LA="black")
visual_inspection<-function(samp){
  plots<-lapply(c("CD10","KRT8","CD45","CD20","PGP95"),function(z) 
    filtered[[samp]]%>%filter(protein==z)%>%ggplot(aes(x=x,y=-y,col=signal))+
    geom_point(size=.1)+scale_color_viridis_c(option = 'H')+ggtitle(z))
  plots[[6]]<-filtered[[samp]]%>%
    ggplot(aes(x=x,y=-y,col=protein))+geom_point(size=.1)+
    guides(col=guide_legend(override.aes = list(size=5)))+
    scale_color_manual(values=protecols)
  gridExtra::grid.arrange(grobs=plots)}
summary_plots<-lapply(names(filtered),visual_inspection)
names(summary_plots)<-names(data)
```

```{r}
temp<-lapply(filtered,function(x) x%>%filter(protein%in%c("CD20","CD45")))
for (i in names(temp)) {
    temp[[i]]$cl<-dbscan(temp[[i]][,1:2],eps = 10,minPts = 30)$cluster
}
temp<-lapply(temp,function(x) 
    x%>%filter(cl!=0)%>%ungroup())
lapply(names(temp), function(x) filtered[[x]]%>%left_join(temp[[x]])%>%
    mutate(protein=ifelse(!is.na(cl),"LA",protein))%>%ggplot(aes(x=x,y=-y,col=protein))+
    geom_point(size=.1)+scale_color_manual(values=protecols)+
    guides(col=guide_legend(override.aes = list(size=3))))
temp<-lapply(names(filtered),function(x)
    filtered[[x]]%>%left_join(temp[[x]])%>%filter(protein=="PGP95"|!is.na(cl)))
names(temp)<-names(filtered)

neuro_CD20_dist<-function(samp){
     neuro_CD20<-temp[[samp]]
     distmat<-as.matrix(dist(neuro_CD20[,3:4]))
     i<-which(neuro_CD20$protein!="PGP95")
     j<-which(neuro_CD20$protein=="PGP95")
     distmat<-distmat[j,i]
     mindists<-apply(distmat,1,min)
return(mindists)}
res<-lapply(names(filtered),neuro_CD20_dist)
names(res)<-names(filtered)
res<-as.data.frame(unlist(res))%>%rownames_to_column("sample")%>%
  separate(sample,into = c("sample","neuro_pixel"),sep = '\\.')
colnames(res)[3]<-"dist_to_CD20"

p0<-res%>%ggplot(aes(x=sample,y=dist_to_CD20))+geom_violin()+
  geom_jitter(width=.1,alpha=0.5)+geom_boxplot(width=.1,alpha=0.5)
res<-res%>%mutate(has_LA=ifelse(sample%in%c("SL260087","SL260088","SL260089"),
  "LA+","LA-"))
p1<-res%>%ggplot(aes(x=has_LA,y=dist_to_CD20))+geom_violin()+
  geom_jitter(width=.1,alpha=0.5)+geom_boxplot(width=.1,alpha=0.5)+
  stat_compare_means(label='p.signif',comparisons = list(c("LA+","LA-")))
```

```{r}
temp<-lapply(names(filtered),function(i) 
    filtered[[i]]%>%mutate(Sample=i))%>%bind_rows()%>%
    mutate(has_LA=ifelse(Sample%in%c("SL260087","SL260088","SL260089"),"LA+","LA-"))

